### PR TITLE
Vehicle singleSeat quality fix

### PR DESCRIPTION
**Pull request by lozanoje**
Fix two issues:

1. Key "AC2D20.VEHICLES.QUALITIES.singleSeat" is duplicated, I remove one.
2. Vehicle quality "singleSeat:" changed for "singleSeat", there is an extra ":" at that label.

### CODE REVIEW

**Comment by lozanoje** [comment]
Seems that now quality singleSeat is duplicated, I have to further see whats happening

**Comment by lozanoje** [comment]
False alarm, the duplicated was because I had an old vehicle with the old "singleSeat:" label

**Comment by Muttley** [comment]
Unfortunately it's a bit more complicated than just changing the name.  There needs to be a migration step written to automatically migrate the old named values to the new, otherwise some data could be lost.

**Comment by Muttley** [comment]
Fixed with the following commit: https://github.com/Muttley/foundryvtt-ac2d20/commit/d7172aca835cbf1c60b867a3d76a07334835415d

**Pull request closed without merging**
